version: '3.8'
services:
  nest-api:
    container_name: nest-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - redis
      - postgres
    env_file:
      - .env.local

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env.local
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
volumes:
  postgres_data:
  redis:
    driver: local
